{
  "Software_Repo_MappingId": null,
  "Software_RepoId": "f6b863cd-8f1c-4583-8bc5-ee59e86e5cf1",
  "Software_Name": "Python 3.12.5 (64-bit)",
  "CVEID": "CVE-2004-0150",
  "Summary": "Buffer overflow in the getaddrinfo function in Python 2.2 before 2.2.2, when IPv6 support is disabled, allows remote attackers to execute arbitrary code via an IPv6 address that is obtained using DNS.",
  "LastUpdate": 0,
  "CVEE": {
    "CVEEId": "CVE-2004-0150",
    "CVSS_V2_baseScore": 7.5,
    "CVSS_V2_Data": "{\"version\":\"2.0\",\"baseScore\":7.5,\"accessVector\":\"NETWORK\",\"vectorString\":\"AV:N/AC:L/Au:N/C:P/I:P/A:P\",\"authentication\":\"NONE\",\"integrityImpact\":\"PARTIAL\",\"accessComplexity\":\"LOW\",\"availabilityImpact\":\"PARTIAL\",\"confidentialityImpact\":\"PARTIAL\",\"scope\":null,\"attackVector\":null,\"baseSeverity\":null,\"userInteraction\":null,\"attackComplexity\":null,\"privilegesRequired\":null}",
    "CVSS_V3_baseScore": null,
    "CVSS_V3_Data": null,
    "PublishedDate": "2004-04-15T04:00:00",
    "ModifyDate": "2024-11-20T23:47:52.29",
    "VulnStatus": "Modified",
    "JsonData": "{\"id\": \"CVE-2004-0150\", \"summary\": \"Buffer overflow in the getaddrinfo function in Python 2.2 before 2.2.2, when IPv6 support is disabled, allows remote attackers to execute arbitrary code via an IPv6 address that is obtained using DNS.\", \"created_at\": \"2004-04-15T04:00:00Z\", \"updated_at\": \"2024-11-20T23:47:52Z\", \"cvss\": {\"v2\": 7.5, \"v3\": null}, \"vendors\": {\"python\": [\"python\"]}, \"cwes\": [\"CWE-120\"], \"raw_nvd_data\": {\"id\": \"CVE-2004-0150\", \"metrics\": {\"cvssMetricV2\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"version\": \"2.0\", \"baseScore\": 7.5, \"accessVector\": \"NETWORK\", \"vectorString\": \"AV:N/AC:L/Au:N/C:P/I:P/A:P\", \"authentication\": \"NONE\", \"integrityImpact\": \"PARTIAL\", \"accessComplexity\": \"LOW\", \"availabilityImpact\": \"PARTIAL\", \"confidentialityImpact\": \"PARTIAL\"}, \"acInsufInfo\": false, \"impactScore\": 6.4, \"baseSeverity\": \"HIGH\", \"obtainAllPrivilege\": false, \"exploitabilityScore\": 10.0, \"obtainUserPrivilege\": false, \"obtainOtherPrivilege\": true, \"userInteractionRequired\": false}]}, \"published\": \"2004-04-15T04:00:00.000\", \"references\": [{\"url\": \"http://www.debian.org/security/2004/dsa-458\", \"tags\": [\"Patch\", \"Vendor Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"http://www.gentoo.org/security/en/glsa/glsa-200409-03.xml\", \"tags\": [\"Third Party Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"http://www.mandrakesoft.com/security/advisories?name=MDKSA-2004:019\", \"tags\": [\"Broken Link\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"http://www.osvdb.org/4172\", \"tags\": [\"Broken Link\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"http://www.securityfocus.com/bid/9836\", \"tags\": [\"Patch\", \"Third Party Advisory\", \"VDB Entry\", \"Vendor Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://exchange.xforce.ibmcloud.com/vulnerabilities/15409\", \"tags\": [\"VDB Entry\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"http://www.debian.org/security/2004/dsa-458\", \"tags\": [\"Patch\", \"Vendor Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"http://www.gentoo.org/security/en/glsa/glsa-200409-03.xml\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"http://www.mandrakesoft.com/security/advisories?name=MDKSA-2004:019\", \"tags\": [\"Broken Link\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"http://www.osvdb.org/4172\", \"tags\": [\"Broken Link\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"http://www.securityfocus.com/bid/9836\", \"tags\": [\"Patch\", \"Third Party Advisory\", \"VDB Entry\", \"Vendor Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://exchange.xforce.ibmcloud.com/vulnerabilities/15409\", \"tags\": [\"VDB Entry\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}], \"vulnStatus\": \"Modified\", \"weaknesses\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"description\": [{\"lang\": \"en\", \"value\": \"CWE-120\"}]}], \"descriptions\": [{\"lang\": \"en\", \"value\": \"Buffer overflow in the getaddrinfo function in Python 2.2 before 2.2.2, when IPv6 support is disabled, allows remote attackers to execute arbitrary code via an IPv6 address that is obtained using DNS.\"}, {\"lang\": \"es\", \"value\": \"Desbordamiento de b\\u00fafer en getaddrinfo de Python 2.2 permite a atacantes remotos ejecutar c\\u00f3digo arbitrario mediante una direcci\\u00f3n IPv6 obtenida usando DNS.\"}], \"lastModified\": \"2024-11-20T23:47:52.290\", \"configurations\": [{\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"F186F453-E521-487E-8ADA-1EC726045E7A\", \"versionEndExcluding\": \"2.2.2\", \"versionStartIncluding\": \"2.2.0\"}], \"operator\": \"OR\"}]}], \"sourceIdentifier\": \"cve@mitre.org\"}}\n",
    "LastUpdate": 0,
    "VendorL": [
      "python"
    ],
    "ProductL": [
      "python"
    ],
    "Software_Repo_Mappings": []
  },
  "Software_Repo_Mapping_Conditions": [
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "2.2.2",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "2.2.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    }
  ]
}