{
  "Software_Repo_MappingId": null,
  "Software_RepoId": "f6b863cd-8f1c-4583-8bc5-ee59e86e5cf1",
  "Software_Name": "Python 3.12.5 (64-bit)",
  "CVEID": "CVE-2023-36632",
  "Summary": "The legacy email.utils.parseaddr function in Python through 3.11.4 allows attackers to trigger \"RecursionError: maximum recursion depth exceeded while calling a Python object\" via a crafted argument. This argument is plausibly an untrusted value from an application's input data that was supposed to contain a name and an e-mail address. NOTE: email.utils.parseaddr is categorized as a Legacy API in the documentation of the Python email package. Applications should instead use the email.parser.BytesParser or email.parser.Parser class. NOTE: the vendor's perspective is that this is neither a vulnerability nor a bug. The email package is intended to have size limits and to throw an exception when limits are exceeded; they were exceeded by the example demonstration code.",
  "LastUpdate": 0,
  "CVEE": {
    "CVEEId": "CVE-2023-36632",
    "CVSS_V2_baseScore": null,
    "CVSS_V2_Data": null,
    "CVSS_V3_baseScore": 7.5,
    "CVSS_V3_Data": "{\"version\":\"3.1\",\"baseScore\":7.5,\"accessVector\":null,\"vectorString\":\"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H\",\"authentication\":null,\"integrityImpact\":\"NONE\",\"accessComplexity\":null,\"availabilityImpact\":\"HIGH\",\"confidentialityImpact\":\"NONE\",\"scope\":\"UNCHANGED\",\"attackVector\":\"NETWORK\",\"baseSeverity\":\"HIGH\",\"userInteraction\":\"NONE\",\"attackComplexity\":\"LOW\",\"privilegesRequired\":\"NONE\"}",
    "PublishedDate": "2023-06-25T18:15:09.313",
    "ModifyDate": "2024-11-21T08:10:07.813",
    "VulnStatus": "Modified",
    "JsonData": "{\"id\": \"CVE-2023-36632\", \"summary\": \"The legacy email.utils.parseaddr function in Python through 3.11.4 allows attackers to trigger \\\"RecursionError: maximum recursion depth exceeded while calling a Python object\\\" via a crafted argument. This argument is plausibly an untrusted value from an application's input data that was supposed to contain a name and an e-mail address. NOTE: email.utils.parseaddr is categorized as a Legacy API in the documentation of the Python email package. Applications should instead use the email.parser.BytesParser or email.parser.Parser class. NOTE: the vendor's perspective is that this is neither a vulnerability nor a bug. The email package is intended to have size limits and to throw an exception when limits are exceeded; they were exceeded by the example demonstration code.\", \"created_at\": \"2023-06-25T18:15:09Z\", \"updated_at\": \"2024-11-21T08:10:07Z\", \"cvss\": {\"v2\": null, \"v3\": 7.5}, \"vendors\": {\"python\": [\"python\"]}, \"cwes\": [\"CWE-674\"], \"raw_nvd_data\": {\"id\": \"CVE-2023-36632\", \"cveTags\": [{\"tags\": [\"disputed\"], \"sourceIdentifier\": \"cve@mitre.org\"}], \"metrics\": {\"cvssMetricV31\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"scope\": \"UNCHANGED\", \"version\": \"3.1\", \"baseScore\": 7.5, \"attackVector\": \"NETWORK\", \"baseSeverity\": \"HIGH\", \"vectorString\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H\", \"integrityImpact\": \"NONE\", \"userInteraction\": \"NONE\", \"attackComplexity\": \"LOW\", \"availabilityImpact\": \"HIGH\", \"privilegesRequired\": \"NONE\", \"confidentialityImpact\": \"NONE\"}, \"impactScore\": 3.6, \"exploitabilityScore\": 3.9}]}, \"published\": \"2023-06-25T18:15:09.313\", \"references\": [{\"url\": \"https://docs.python.org/3/library/email.html\", \"tags\": [\"Product\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://docs.python.org/3/library/email.utils.html\", \"tags\": [\"Product\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://github.com/Daybreak2019/PoC_python3.9_Vul/blob/main/RecursionError-email.utils.parseaddr.py\", \"tags\": [\"Product\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://github.com/python/cpython/issues/103800\", \"tags\": [\"Exploit\", \"Issue Tracking\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://docs.python.org/3/library/email.html\", \"tags\": [\"Product\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://docs.python.org/3/library/email.utils.html\", \"tags\": [\"Product\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://github.com/Daybreak2019/PoC_python3.9_Vul/blob/main/RecursionError-email.utils.parseaddr.py\", \"tags\": [\"Product\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://github.com/python/cpython/issues/103800\", \"tags\": [\"Exploit\", \"Issue Tracking\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}], \"vulnStatus\": \"Modified\", \"weaknesses\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"description\": [{\"lang\": \"en\", \"value\": \"CWE-674\"}]}], \"descriptions\": [{\"lang\": \"en\", \"value\": \"The legacy email.utils.parseaddr function in Python through 3.11.4 allows attackers to trigger \\\"RecursionError: maximum recursion depth exceeded while calling a Python object\\\" via a crafted argument. This argument is plausibly an untrusted value from an application's input data that was supposed to contain a name and an e-mail address. NOTE: email.utils.parseaddr is categorized as a Legacy API in the documentation of the Python email package. Applications should instead use the email.parser.BytesParser or email.parser.Parser class. NOTE: the vendor's perspective is that this is neither a vulnerability nor a bug. The email package is intended to have size limits and to throw an exception when limits are exceeded; they were exceeded by the example demonstration code.\"}], \"lastModified\": \"2024-11-21T08:10:07.813\", \"configurations\": [{\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"FBFABA38-746A-451D-A9DB-8AF31A4AE9B3\", \"versionEndIncluding\": \"3.11.4\"}], \"operator\": \"OR\"}]}], \"sourceIdentifier\": \"cve@mitre.org\"}}\n",
    "LastUpdate": 0,
    "VendorL": [
      "python"
    ],
    "ProductL": [
      "python"
    ],
    "Software_Repo_Mappings": []
  },
  "Software_Repo_Mapping_Conditions": [
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": "3.11.4",
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    }
  ]
}