{
  "Software_Repo_MappingId": null,
  "Software_RepoId": "f6b863cd-8f1c-4583-8bc5-ee59e86e5cf1",
  "Software_Name": "Python 3.12.5 (64-bit)",
  "CVEID": "CVE-2023-41105",
  "Summary": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
  "LastUpdate": 0,
  "CVEE": {
    "CVEEId": "CVE-2023-41105",
    "CVSS_V2_baseScore": null,
    "CVSS_V2_Data": null,
    "CVSS_V3_baseScore": 7.5,
    "CVSS_V3_Data": "{\"version\":\"3.1\",\"baseScore\":7.5,\"accessVector\":null,\"vectorString\":\"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N\",\"authentication\":null,\"integrityImpact\":\"HIGH\",\"accessComplexity\":null,\"availabilityImpact\":\"NONE\",\"confidentialityImpact\":\"NONE\",\"scope\":\"UNCHANGED\",\"attackVector\":\"NETWORK\",\"baseSeverity\":\"HIGH\",\"userInteraction\":\"NONE\",\"attackComplexity\":\"LOW\",\"privilegesRequired\":\"NONE\"}",
    "PublishedDate": "2023-08-23T07:15:08.59",
    "ModifyDate": "2024-11-21T08:20:35.71",
    "VulnStatus": "Modified",
    "JsonData": "{\"id\": \"CVE-2023-41105\", \"summary\": \"An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.\", \"created_at\": \"2023-08-23T07:15:08Z\", \"updated_at\": \"2024-11-21T08:20:35Z\", \"cvss\": {\"v2\": null, \"v3\": 7.5}, \"vendors\": {\"python\": [\"python\"], \"netapp\": [\"active_iq_unified_manager\"]}, \"cwes\": [\"CWE-426\"], \"raw_nvd_data\": {\"id\": \"CVE-2023-41105\", \"metrics\": {\"cvssMetricV31\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"scope\": \"UNCHANGED\", \"version\": \"3.1\", \"baseScore\": 7.5, \"attackVector\": \"NETWORK\", \"baseSeverity\": \"HIGH\", \"vectorString\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N\", \"integrityImpact\": \"HIGH\", \"userInteraction\": \"NONE\", \"attackComplexity\": \"LOW\", \"availabilityImpact\": \"NONE\", \"privilegesRequired\": \"NONE\", \"confidentialityImpact\": \"NONE\"}, \"impactScore\": 3.6, \"exploitabilityScore\": 3.9}]}, \"published\": \"2023-08-23T07:15:08.590\", \"references\": [{\"url\": \"https://github.com/python/cpython/issues/106242\", \"tags\": [\"Issue Tracking\", \"Patch\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://github.com/python/cpython/pull/107981\", \"tags\": [\"Patch\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://github.com/python/cpython/pull/107982\", \"tags\": [\"Patch\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://github.com/python/cpython/pull/107983\", \"tags\": [\"Patch\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://mail.python.org/archives/list/security-announce%40python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/\", \"source\": \"cve@mitre.org\"}, {\"url\": \"https://security.netapp.com/advisory/ntap-20231006-0015/\", \"tags\": [\"Third Party Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://github.com/python/cpython/issues/106242\", \"tags\": [\"Issue Tracking\", \"Patch\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://github.com/python/cpython/pull/107981\", \"tags\": [\"Patch\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://github.com/python/cpython/pull/107982\", \"tags\": [\"Patch\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://github.com/python/cpython/pull/107983\", \"tags\": [\"Patch\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://mail.python.org/archives/list/security-announce%40python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://security.netapp.com/advisory/ntap-20231006-0015/\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}], \"vulnStatus\": \"Modified\", \"weaknesses\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"description\": [{\"lang\": \"en\", \"value\": \"CWE-426\"}]}], \"descriptions\": [{\"lang\": \"en\", \"value\": \"An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.\"}], \"lastModified\": \"2024-11-21T08:20:35.710\", \"configurations\": [{\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"445B042E-9410-42E8-8749-A5EAEF2FF93D\", \"versionEndIncluding\": \"3.11.4\", \"versionStartIncluding\": \"3.11.0\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:netapp:active_iq_unified_manager:-:*:*:*:*:windows:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"B55E8D50-99B4-47EC-86F9-699B67D473CE\"}], \"operator\": \"OR\"}]}], \"sourceIdentifier\": \"cve@mitre.org\"}}\n",
    "LastUpdate": 0,
    "VendorL": [
      "python",
      "netapp"
    ],
    "ProductL": [
      "python",
      "active_iq_unified_manager"
    ],
    "Software_Repo_Mappings": []
  },
  "Software_Repo_Mapping_Conditions": [
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": "3.11.4",
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.11.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    }
  ]
}