{
  "Software_Repo_MappingId": null,
  "Software_RepoId": "f6b863cd-8f1c-4583-8bc5-ee59e86e5cf1",
  "Software_Name": "Python 3.12.5 (64-bit)",
  "CVEID": "CVE-2021-3426",
  "Summary": "There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.",
  "LastUpdate": 0,
  "CVEE": {
    "CVEEId": "CVE-2021-3426",
    "CVSS_V2_baseScore": 2.7,
    "CVSS_V2_Data": "{\"version\":\"2.0\",\"baseScore\":2.7,\"accessVector\":\"ADJACENT_NETWORK\",\"vectorString\":\"AV:A/AC:L/Au:S/C:P/I:N/A:N\",\"authentication\":\"SINGLE\",\"integrityImpact\":\"NONE\",\"accessComplexity\":\"LOW\",\"availabilityImpact\":\"NONE\",\"confidentialityImpact\":\"PARTIAL\",\"scope\":null,\"attackVector\":null,\"baseSeverity\":null,\"userInteraction\":null,\"attackComplexity\":null,\"privilegesRequired\":null}",
    "CVSS_V3_baseScore": 5.7,
    "CVSS_V3_Data": "{\"version\":\"3.1\",\"baseScore\":5.7,\"accessVector\":null,\"vectorString\":\"CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N\",\"authentication\":null,\"integrityImpact\":\"NONE\",\"accessComplexity\":null,\"availabilityImpact\":\"NONE\",\"confidentialityImpact\":\"HIGH\",\"scope\":\"UNCHANGED\",\"attackVector\":\"ADJACENT_NETWORK\",\"baseSeverity\":\"MEDIUM\",\"userInteraction\":\"NONE\",\"attackComplexity\":\"LOW\",\"privilegesRequired\":\"LOW\"}",
    "PublishedDate": "2021-05-20T13:15:07.753",
    "ModifyDate": "2024-11-21T06:21:28.65",
    "VulnStatus": "Modified",
    "JsonData": "{\"id\": \"CVE-2021-3426\", \"summary\": \"There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.\", \"created_at\": \"2021-05-20T13:15:07Z\", \"updated_at\": \"2024-11-21T06:21:28Z\", \"cvss\": {\"v2\": 2.7, \"v3\": 5.7}, \"vendors\": {\"oracle\": [\"communications_cloud_native_core_binding_support_function\", \"zfs_storage_appliance_kit\"], \"redhat\": [\"software_collections\", \"enterprise_linux\"], \"netapp\": [\"ontap_select_deploy_administration_utility\", \"snapcenter\", \"cloud_backup\"], \"python\": [\"python\"], \"debian\": [\"debian_linux\"], \"fedoraproject\": [\"fedora\"]}, \"cwes\": [\"CWE-22\", \"CWE-200\"], \"raw_nvd_data\": {\"id\": \"CVE-2021-3426\", \"metrics\": {\"cvssMetricV2\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"version\": \"2.0\", \"baseScore\": 2.7, \"accessVector\": \"ADJACENT_NETWORK\", \"vectorString\": \"AV:A/AC:L/Au:S/C:P/I:N/A:N\", \"authentication\": \"SINGLE\", \"integrityImpact\": \"NONE\", \"accessComplexity\": \"LOW\", \"availabilityImpact\": \"NONE\", \"confidentialityImpact\": \"PARTIAL\"}, \"acInsufInfo\": false, \"impactScore\": 2.9, \"baseSeverity\": \"LOW\", \"obtainAllPrivilege\": false, \"exploitabilityScore\": 5.1, \"obtainUserPrivilege\": false, \"obtainOtherPrivilege\": false, \"userInteractionRequired\": false}], \"cvssMetricV31\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"scope\": \"UNCHANGED\", \"version\": \"3.1\", \"baseScore\": 5.7, \"attackVector\": \"ADJACENT_NETWORK\", \"baseSeverity\": \"MEDIUM\", \"vectorString\": \"CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N\", \"integrityImpact\": \"NONE\", \"userInteraction\": \"NONE\", \"attackComplexity\": \"LOW\", \"availabilityImpact\": \"NONE\", \"privilegesRequired\": \"LOW\", \"confidentialityImpact\": \"HIGH\"}, \"impactScore\": 3.6, \"exploitabilityScore\": 2.1}]}, \"published\": \"2021-05-20T13:15:07.753\", \"references\": [{\"url\": \"https://bugzilla.redhat.com/show_bug.cgi?id=1935913\", \"tags\": [\"Issue Tracking\", \"Patch\", \"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html\", \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/25HVHLBGO2KNPXJ3G426QEYSSCECJDU5/\", \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BF2K7HEWADHN6P52R3QLIOX27U3DJ4HI/\", \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/DQYPUKLLBOZMKFPO7RD7CENTXHUUEUV7/\", \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LM5V4VPLBHBEASSAROYPSHXGXGGPHNOE/\", \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6VXJZSZ6N64AILJX4CTMACYGQGHHD5C/\", \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QNGAFMPIYIVJ47FCF2NK2PIX22HUG35B/\", \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VPX7Y5GQDNB4FJTREWONGC4ZSVH7TGHF/\", \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://security.gentoo.org/glsa/202104-04\", \"tags\": [\"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://security.netapp.com/advisory/ntap-20210629-0003/\", \"tags\": [\"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://www.oracle.com/security-alerts/cpujan2022.html\", \"tags\": [\"Patch\", \"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://www.oracle.com/security-alerts/cpuoct2021.html\", \"tags\": [\"Patch\", \"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"https://bugzilla.redhat.com/show_bug.cgi?id=1935913\", \"tags\": [\"Issue Tracking\", \"Patch\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/25HVHLBGO2KNPXJ3G426QEYSSCECJDU5/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BF2K7HEWADHN6P52R3QLIOX27U3DJ4HI/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/DQYPUKLLBOZMKFPO7RD7CENTXHUUEUV7/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LM5V4VPLBHBEASSAROYPSHXGXGGPHNOE/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6VXJZSZ6N64AILJX4CTMACYGQGHHD5C/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QNGAFMPIYIVJ47FCF2NK2PIX22HUG35B/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VPX7Y5GQDNB4FJTREWONGC4ZSVH7TGHF/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://security.gentoo.org/glsa/202104-04\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://security.netapp.com/advisory/ntap-20210629-0003/\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://www.oracle.com/security-alerts/cpujan2022.html\", \"tags\": [\"Patch\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://www.oracle.com/security-alerts/cpuoct2021.html\", \"tags\": [\"Patch\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}], \"vulnStatus\": \"Modified\", \"weaknesses\": [{\"type\": \"Secondary\", \"source\": \"secalert@redhat.com\", \"description\": [{\"lang\": \"en\", \"value\": \"CWE-200\"}]}, {\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"description\": [{\"lang\": \"en\", \"value\": \"CWE-22\"}]}], \"descriptions\": [{\"lang\": \"en\", \"value\": \"There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.\"}, {\"lang\": \"es\", \"value\": \"Se presenta un fallo en pydoc de Python versi\\u00f3n 3.&#xa0;Un atacante local o adyacente que descubre o es capaz de convencer a otro usuario local o adyacente para que iniciar un servidor pydoc podr\\u00eda acceder al servidor y usarlo para divulgar informaci\\u00f3n confidencial perteneciente al otro usuario al que normalmente no podr\\u00eda acceder.&#xa0;El mayor riesgo de este fallo es la confidencialidad de los datos.&#xa0;Este fallo afecta a Python versiones anteriores a 3.8.9, Python versiones anteriores a 3.9.3 y Python versiones anteriores a 3.10.0a7\"}], \"lastModified\": \"2024-11-21T06:21:28.650\", \"configurations\": [{\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"24C4B7E3-D11A-49D8-90D6-22B61BC970E6\", \"versionEndExcluding\": \"2.7.18\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"9B25D15A-4F2D-4EE0-AE61-CAA5DC478383\", \"versionEndExcluding\": \"3.6.13\", \"versionStartIncluding\": \"3.6.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"EEB52F35-D464-4C26-A253-1B96B2A4921A\", \"versionEndExcluding\": \"3.7.10\", \"versionStartIncluding\": \"3.7.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"8F40C09A-B9FD-40D7-B0A3-89C13DAD040B\", \"versionEndExcluding\": \"3.8.8\", \"versionStartIncluding\": \"3.8.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"B19E0ABC-7E51-4870-BE02-F9D41409BE58\", \"versionEndExcluding\": \"3.9.3\", \"versionStartIncluding\": \"3.9.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:3.10.0:alpha1:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"D3A22303-914F-4EB6-9CCE-EE0D5EDB424B\"}, {\"criteria\": \"cpe:2.3:a:python:python:3.10.0:alpha2:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"349F5466-4F47-47FB-B600-55DB4F919E1A\"}, {\"criteria\": \"cpe:2.3:a:python:python:3.10.0:alpha3:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"14EE982A-1DA9-4D34-B748-862DE731BE69\"}, {\"criteria\": \"cpe:2.3:a:python:python:3.10.0:alpha4:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"D0B1D471-35D3-4289-8C74-63C36233C18D\"}, {\"criteria\": \"cpe:2.3:a:python:python:3.10.0:alpha5:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"D613BB2D-D583-44CC-9C22-38CE434FDDFD\"}, {\"criteria\": \"cpe:2.3:a:python:python:3.10.0:alpha6:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"2075995B-9D49-4EFE-9743-5ACE0B6DEF62\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:o:fedoraproject:fedora:32:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"36D96259-24BD-44E2-96D9-78CE1D41F956\"}, {\"criteria\": \"cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"E460AA51-FCDA-46B9-AE97-E6676AA5E194\"}, {\"criteria\": \"cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"A930E247-0B43-43CB-98FF-6CE7B8189835\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"DEECE5FC-CACF-4496-A3E7-164736409252\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:redhat:software_collections:-:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"749804DA-4B27-492A-9ABA-6BB562A6B3AC\"}, {\"criteria\": \"cpe:2.3:o:redhat:enterprise_linux:8.0:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"F4CFF558-3C47-480D-A2F0-BABF26042943\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:netapp:cloud_backup:-:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"5C2089EE-5D7F-47EC-8EA5-0F69790564C4\"}, {\"criteria\": \"cpe:2.3:a:netapp:ontap_select_deploy_administration_utility:-:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"E7CF3019-975D-40BB-A8A4-894E62BD3797\"}, {\"criteria\": \"cpe:2.3:a:netapp:snapcenter:-:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"BDFB1169-41A0-4A86-8E4F-FDA9730B1E94\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:oracle:communications_cloud_native_core_binding_support_function:1.10.0:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"B6B6FE82-7BFA-481D-99D6-789B146CA18B\"}, {\"criteria\": \"cpe:2.3:a:oracle:zfs_storage_appliance_kit:8.8:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"D3E503FB-6279-4D4A-91D8-E237ECF9D2B0\"}], \"operator\": \"OR\"}]}], \"sourceIdentifier\": \"secalert@redhat.com\"}}\n",
    "LastUpdate": 0,
    "VendorL": [
      "oracle",
      "redhat",
      "netapp",
      "python",
      "debian",
      "fedoraproject"
    ],
    "ProductL": [
      "communications_cloud_native_core_binding_support_function",
      "zfs_storage_appliance_kit",
      "software_collections",
      "enterprise_linux",
      "ontap_select_deploy_administration_utility",
      "snapcenter",
      "cloud_backup",
      "python",
      "debian_linux",
      "fedora"
    ],
    "Software_Repo_Mappings": []
  },
  "Software_Repo_Mapping_Conditions": [
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "2.7.18",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.6.13",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.6.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.7.10",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.7.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.8.8",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.8.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.9.3",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.9.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:3.10.0:alpha1:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:3.10.0:alpha2:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:3.10.0:alpha3:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:3.10.0:alpha4:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:3.10.0:alpha5:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:3.10.0:alpha6:*:*:*:*:*:*",
      "VersionEndExcluding": null,
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    }
  ]
}