{
  "Software_Repo_MappingId": null,
  "Software_RepoId": "f6b863cd-8f1c-4583-8bc5-ee59e86e5cf1",
  "Software_Name": "Python 3.12.5 (64-bit)",
  "CVEID": "CVE-2017-1000158",
  "Summary": "CPython (aka Python) up to 2.7.13 is vulnerable to an integer overflow in the PyString_DecodeEscape function in stringobject.c, resulting in heap-based buffer overflow (and possible arbitrary code execution)",
  "LastUpdate": 0,
  "CVEE": {
    "CVEEId": "CVE-2017-1000158",
    "CVSS_V2_baseScore": 7.5,
    "CVSS_V2_Data": "{\"version\":\"2.0\",\"baseScore\":7.5,\"accessVector\":\"NETWORK\",\"vectorString\":\"AV:N/AC:L/Au:N/C:P/I:P/A:P\",\"authentication\":\"NONE\",\"integrityImpact\":\"PARTIAL\",\"accessComplexity\":\"LOW\",\"availabilityImpact\":\"PARTIAL\",\"confidentialityImpact\":\"PARTIAL\",\"scope\":null,\"attackVector\":null,\"baseSeverity\":null,\"userInteraction\":null,\"attackComplexity\":null,\"privilegesRequired\":null}",
    "CVSS_V3_baseScore": 9.8,
    "CVSS_V3_Data": "{\"version\":\"3.1\",\"baseScore\":9.8,\"accessVector\":null,\"vectorString\":\"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H\",\"authentication\":null,\"integrityImpact\":\"HIGH\",\"accessComplexity\":null,\"availabilityImpact\":\"HIGH\",\"confidentialityImpact\":\"HIGH\",\"scope\":\"UNCHANGED\",\"attackVector\":\"NETWORK\",\"baseSeverity\":\"CRITICAL\",\"userInteraction\":\"NONE\",\"attackComplexity\":\"LOW\",\"privilegesRequired\":\"NONE\"}",
    "PublishedDate": "2017-11-17T05:29:00.28",
    "ModifyDate": "2024-11-21T03:04:18.213",
    "VulnStatus": "Modified",
    "JsonData": "{\"id\": \"CVE-2017-1000158\", \"summary\": \"CPython (aka Python) up to 2.7.13 is vulnerable to an integer overflow in the PyString_DecodeEscape function in stringobject.c, resulting in heap-based buffer overflow (and possible arbitrary code execution)\", \"created_at\": \"2017-11-17T05:29:00Z\", \"updated_at\": \"2024-11-21T03:04:18Z\", \"cvss\": {\"v2\": 7.5, \"v3\": 9.8}, \"vendors\": {\"python\": [\"python\"], \"debian\": [\"debian_linux\"]}, \"cwes\": [\"CWE-190\"], \"raw_nvd_data\": {\"id\": \"CVE-2017-1000158\", \"metrics\": {\"cvssMetricV2\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"version\": \"2.0\", \"baseScore\": 7.5, \"accessVector\": \"NETWORK\", \"vectorString\": \"AV:N/AC:L/Au:N/C:P/I:P/A:P\", \"authentication\": \"NONE\", \"integrityImpact\": \"PARTIAL\", \"accessComplexity\": \"LOW\", \"availabilityImpact\": \"PARTIAL\", \"confidentialityImpact\": \"PARTIAL\"}, \"acInsufInfo\": false, \"impactScore\": 6.4, \"baseSeverity\": \"HIGH\", \"obtainAllPrivilege\": false, \"exploitabilityScore\": 10.0, \"obtainUserPrivilege\": false, \"obtainOtherPrivilege\": false, \"userInteractionRequired\": false}], \"cvssMetricV31\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"scope\": \"UNCHANGED\", \"version\": \"3.1\", \"baseScore\": 9.8, \"attackVector\": \"NETWORK\", \"baseSeverity\": \"CRITICAL\", \"vectorString\": \"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H\", \"integrityImpact\": \"HIGH\", \"userInteraction\": \"NONE\", \"attackComplexity\": \"LOW\", \"availabilityImpact\": \"HIGH\", \"privilegesRequired\": \"NONE\", \"confidentialityImpact\": \"HIGH\"}, \"impactScore\": 5.9, \"exploitabilityScore\": 3.9}]}, \"published\": \"2017-11-17T05:29:00.280\", \"references\": [{\"url\": \"http://www.securitytracker.com/id/1039890\", \"tags\": [\"Third Party Advisory\", \"VDB Entry\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://bugs.python.org/issue30657\", \"tags\": [\"Issue Tracking\", \"Patch\", \"Vendor Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2017/11/msg00035.html\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2017/11/msg00036.html\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://security.gentoo.org/glsa/201805-02\", \"tags\": [\"Third Party Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"https://security.netapp.com/advisory/ntap-20230216-0001/\", \"source\": \"cve@mitre.org\"}, {\"url\": \"https://www.debian.org/security/2018/dsa-4307\", \"tags\": [\"Third Party Advisory\"], \"source\": \"cve@mitre.org\"}, {\"url\": \"http://www.securitytracker.com/id/1039890\", \"tags\": [\"Third Party Advisory\", \"VDB Entry\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://bugs.python.org/issue30657\", \"tags\": [\"Issue Tracking\", \"Patch\", \"Vendor Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2017/11/msg00035.html\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2017/11/msg00036.html\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://security.gentoo.org/glsa/201805-02\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://security.netapp.com/advisory/ntap-20230216-0001/\", \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"https://www.debian.org/security/2018/dsa-4307\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}], \"vulnStatus\": \"Modified\", \"weaknesses\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"description\": [{\"lang\": \"en\", \"value\": \"CWE-190\"}]}], \"descriptions\": [{\"lang\": \"en\", \"value\": \"CPython (aka Python) up to 2.7.13 is vulnerable to an integer overflow in the PyString_DecodeEscape function in stringobject.c, resulting in heap-based buffer overflow (and possible arbitrary code execution)\"}, {\"lang\": \"es\", \"value\": \"CPython (tambi\\u00e9n conocido como Python) hasta la versi\\u00f3n 2.7.13 es vulnerable a un desbordamiento de enteros en la funci\\u00f3n PyString_DecodeEscape en stringobject.c, lo que resulta en un desbordamiento de b\\u00fafer basado en memoria din\\u00e1mica (heap) y, posiblemente, la ejecuci\\u00f3n de c\\u00f3digo arbitrario.\"}], \"lastModified\": \"2024-11-21T03:04:18.213\", \"configurations\": [{\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"B3B9C8F1-930A-4904-BA58-CD71AEA6F041\", \"versionEndExcluding\": \"2.7.15\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"7100BA3C-4470-4326-A3B2-16C0DF8B7FA0\", \"versionEndExcluding\": \"3.4.8\", \"versionStartIncluding\": \"3.4.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"2525C259-8A44-4DB5-939F-D5B808470669\", \"versionEndExcluding\": \"3.5.5\", \"versionStartIncluding\": \"3.5.0\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:o:debian:debian_linux:7.0:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"16F59A04-14CF-49E2-9973-645477EA09DA\"}, {\"criteria\": \"cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"C11E6FB0-C8C0-4527-9AA0-CB9B316F8F43\"}, {\"criteria\": \"cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"DEECE5FC-CACF-4496-A3E7-164736409252\"}], \"operator\": \"OR\"}]}], \"sourceIdentifier\": \"cve@mitre.org\"}}\n",
    "LastUpdate": 0,
    "VendorL": [
      "python",
      "debian"
    ],
    "ProductL": [
      "python",
      "debian_linux"
    ],
    "Software_Repo_Mappings": []
  },
  "Software_Repo_Mapping_Conditions": [
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "2.7.15",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": null,
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.4.8",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.4.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.5.5",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.5.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    }
  ]
}