{
  "Software_Repo_MappingId": null,
  "Software_RepoId": "f6b863cd-8f1c-4583-8bc5-ee59e86e5cf1",
  "Software_Name": "Python 3.12.5 (64-bit)",
  "CVEID": "CVE-2012-2135",
  "Summary": "The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors.",
  "LastUpdate": 0,
  "CVEE": {
    "CVEEId": "CVE-2012-2135",
    "CVSS_V2_baseScore": 6.4,
    "CVSS_V2_Data": "{\"version\":\"2.0\",\"baseScore\":6.4,\"accessVector\":\"NETWORK\",\"vectorString\":\"AV:N/AC:L/Au:N/C:P/I:N/A:P\",\"authentication\":\"NONE\",\"integrityImpact\":\"NONE\",\"accessComplexity\":\"LOW\",\"availabilityImpact\":\"PARTIAL\",\"confidentialityImpact\":\"PARTIAL\",\"scope\":null,\"attackVector\":null,\"baseSeverity\":null,\"userInteraction\":null,\"attackComplexity\":null,\"privilegesRequired\":null}",
    "CVSS_V3_baseScore": null,
    "CVSS_V3_Data": null,
    "PublishedDate": "2012-08-14T22:55:01.253",
    "ModifyDate": "2024-11-21T01:38:34.297",
    "VulnStatus": "Modified",
    "JsonData": "{\"id\": \"CVE-2012-2135\", \"summary\": \"The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors.\", \"created_at\": \"2012-08-14T22:55:01Z\", \"updated_at\": \"2024-11-21T01:38:34Z\", \"cvss\": {\"v2\": 6.4, \"v3\": null}, \"vendors\": {\"python\": [\"python\"], \"debian\": [\"debian_linux\"], \"canonical\": [\"ubuntu_linux\"]}, \"cwes\": [\"NVD-CWE-Other\"], \"raw_nvd_data\": {\"id\": \"CVE-2012-2135\", \"metrics\": {\"cvssMetricV2\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"cvssData\": {\"version\": \"2.0\", \"baseScore\": 6.4, \"accessVector\": \"NETWORK\", \"vectorString\": \"AV:N/AC:L/Au:N/C:P/I:N/A:P\", \"authentication\": \"NONE\", \"integrityImpact\": \"NONE\", \"accessComplexity\": \"LOW\", \"availabilityImpact\": \"PARTIAL\", \"confidentialityImpact\": \"PARTIAL\"}, \"acInsufInfo\": false, \"impactScore\": 4.9, \"baseSeverity\": \"MEDIUM\", \"obtainAllPrivilege\": false, \"exploitabilityScore\": 10.0, \"obtainUserPrivilege\": false, \"obtainOtherPrivilege\": false, \"userInteractionRequired\": false}]}, \"published\": \"2012-08-14T22:55:01.253\", \"references\": [{\"url\": \"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389\", \"tags\": [\"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"http://bugs.python.org/issue14579\", \"tags\": [\"Vendor Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"http://secunia.com/advisories/51087\", \"tags\": [\"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"http://secunia.com/advisories/51089\", \"tags\": [\"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"http://www.openwall.com/lists/oss-security/2012/04/25/2\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"http://www.openwall.com/lists/oss-security/2012/04/25/4\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"http://www.ubuntu.com/usn/USN-1615-1\", \"tags\": [\"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"http://www.ubuntu.com/usn/USN-1616-1\", \"tags\": [\"Third Party Advisory\"], \"source\": \"secalert@redhat.com\"}, {\"url\": \"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"http://bugs.python.org/issue14579\", \"tags\": [\"Vendor Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"http://secunia.com/advisories/51087\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"http://secunia.com/advisories/51089\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"http://www.openwall.com/lists/oss-security/2012/04/25/2\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"http://www.openwall.com/lists/oss-security/2012/04/25/4\", \"tags\": [\"Mailing List\", \"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"http://www.ubuntu.com/usn/USN-1615-1\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}, {\"url\": \"http://www.ubuntu.com/usn/USN-1616-1\", \"tags\": [\"Third Party Advisory\"], \"source\": \"af854a3a-2127-422b-91ae-364da2661108\"}], \"vulnStatus\": \"Modified\", \"weaknesses\": [{\"type\": \"Primary\", \"source\": \"nvd@nist.gov\", \"description\": [{\"lang\": \"en\", \"value\": \"NVD-CWE-Other\"}]}], \"descriptions\": [{\"lang\": \"en\", \"value\": \"The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors.\"}, {\"lang\": \"es\", \"value\": \"El descodificador UTF-16 en Python v3.1 a v3.3 no actualiza la variable aligned_end despu\\u00e9s de llamar a la funci\\u00f3n unicode_decode_call_errorhandler, lo que permite a atacantes remotos obtener informaci\\u00f3n sensible (la memoria del proceso) o provocar una denegaci\\u00f3n de servicio (por corrupci\\u00f3n de memoria y ca\\u00edda la aplicaci\\u00f3n) a trav\\u00e9s de vectores no especificados.\\r\\n\"}], \"lastModified\": \"2024-11-21T01:38:34.297\", \"configurations\": [{\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"A599D400-4DFF-45E9-869D-4C51FC04B520\", \"versionEndExcluding\": \"2.7.4\", \"versionStartIncluding\": \"2.7.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"D2CC57DA-61B2-4C5D-BDC4-7430912BD702\", \"versionEndExcluding\": \"3.2.4\", \"versionStartIncluding\": \"3.2.0\"}, {\"criteria\": \"cpe:2.3:a:python:python:*:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"FD5652D5-BBAF-4BEC-82C3-5CB960846578\", \"versionEndExcluding\": \"3.3.3\", \"versionStartIncluding\": \"3.3.0\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:o:canonical:ubuntu_linux:10.04:*:*:*:-:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"01EDA41C-6B2E-49AF-B503-EB3882265C11\"}, {\"criteria\": \"cpe:2.3:o:canonical:ubuntu_linux:11.04:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"EF49D26F-142E-468B-87C1-BABEA445255C\"}, {\"criteria\": \"cpe:2.3:o:canonical:ubuntu_linux:11.10:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"E4174F4F-149E-41A6-BBCC-D01114C05F38\"}, {\"criteria\": \"cpe:2.3:o:canonical:ubuntu_linux:12.04:*:*:*:-:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"CB66DB75-2B16-4EBF-9B93-CE49D8086E41\"}, {\"criteria\": \"cpe:2.3:o:canonical:ubuntu_linux:12.10:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"E2076871-2E80-4605-A470-A41C1A8EC7EE\"}], \"operator\": \"OR\"}]}, {\"nodes\": [{\"negate\": false, \"cpeMatch\": [{\"criteria\": \"cpe:2.3:o:debian:debian_linux:6.0:*:*:*:*:*:*:*\", \"vulnerable\": true, \"matchCriteriaId\": \"036E8A89-7A16-411F-9D31-676313BB7244\"}], \"operator\": \"OR\"}]}], \"sourceIdentifier\": \"secalert@redhat.com\"}}\n",
    "LastUpdate": 0,
    "VendorL": [
      "python",
      "debian",
      "canonical"
    ],
    "ProductL": [
      "python",
      "debian_linux",
      "ubuntu_linux"
    ],
    "Software_Repo_Mappings": []
  },
  "Software_Repo_Mapping_Conditions": [
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "2.7.4",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "2.7.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.2.4",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.2.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    },
    {
      "Software_Repo_Mapping_ConditionId": 0,
      "Software_Repo_MappingId": null,
      "Criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "VersionEndExcluding": "3.3.3",
      "VersionEndIncluding": null,
      "VersionStartExcluding": null,
      "VersionStartIncluding": "3.3.0",
      "Vulnerable": true,
      "Software_Repo_Mapping": null
    }
  ]
}